server:
  port: 8888
spring:
    application:
        name: ek-server
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mydb
        username: root
        password: pwd
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
mybatis-plus:
  #信息输出设置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

